apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demopvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce                  # ReadWriteOnce, ReadWriteMany, ReadOnlyMany, ReadWriteOncePod

---
# Create a PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  storageClassName: ""
  volumeName: ebs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi