apiVersion: v1
kind: Pod
metadata:
  name: ckad-neighbor-pod
  namespace: ckad-multi-containers
  labels:
    app: ckad-neighbor-pod
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: main-container
    image: nginx:1.16
    volumeMounts:
    - name: my-vol
      mountPath: /usr/share/nginx/html
  - name: neighbor-container
    image: busybox:1.28
    command: ['sh', '-c', 'top']
    volumeMounts:
    - name: my-vol
      mountPath: /var/log
  volumes:
  - name: my-vol
    emptyDir: {}
  
---
apiVersion: v1
kind: Pod
metadata:
  name: ckad-redis-wiipwlznjy
  namespace: ckad-pod-design
  annotations:
    KKE: "https://engineer.kodekloud.com/"
  labels:
    app: ckad-redis-wiipwlznjy
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: redis-custom-annotation
    image: redis
---
apiVersion: v1
kind: Pod
metadata:
  name: name
  labels:
    app: name
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: name
    image: image
    imagePullPolicy: IfNotPresent  # Always, IfNotPresent, Never
    ports:
    - containerPort: port 
    env:
    - name: name
      valueFrom:
        configMapKeyRef:
          name: config
          key: key

---
apiVersion: v1
kind: Pod
metadata:
  name: ckad15-memory
  labels:
    app: ckad15-memory
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: ckad15-memory
    image: polinux/stress
    command:
    - /bin/sh
    - -c
    - "stress --vm 1 --vm-bytes 10M --vm-hang 1"
    resources:
      requests:
        memory: 10Mi
      limits:
        memory: 10Mi
