apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-deploy
  namespace: default
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: sa-app
  template:
    metadata:
      labels:
        app: sa-app
    spec:
      serviceAccountName: sa-app
      restartPolicy: Always            # Always, OnFailure, Never
      containers:
      - name: sa-deploy-cont
        image: gcr.io/kodekloud/customimage/my-kubernetes-dashboard
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: sa-service
spec:
  selector:
    app: sa-app
  type: NodePort                      # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007               # 30000-32767

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, watch]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: sa-app
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
