apiVersion: v1
kind: ServiceAccount
metadata:
  name: john
  namespace: default
secrets: 
  - name: john-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: john-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: john
type: kubernetes.io/service-account-token


---
# Get the secret name
kubectl get serviceaccount john -o jsonpath='{.secrets[0].name}'

# Retrieve the token
# kubectl get secret john-secret -o jsonpath='{.data.token}' | base64 --decode

# Save the token to a file
# kubectl get secret john-secret -o jsonpath='{.data.token}' | base64 --decode > john-secret.txt