apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demopvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce                  # ReadWriteOnce, ReadWriteMany, ReadOnlyMany, ReadWriteOncePod