apiVersion: v1
kind: Pod
metadata:
  name: pvpod3
  labels:
    app: pvpod
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: pvpod
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: pv-volume
  tolerations:
    - key: node
      operator: Equal
      value: two
      effect: NoSchedule
  volumes:
    - name: pv-volume
      persistentVolumeClaim:
        claimName: demopvc

---
# Create a pod using the PVC
apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: app
    image: busybox
    command: [ "sh", "-c", "echo Hello Kubernetes! && sleep 3600" ]
    volumeMounts:
    - mountPath: "/data"
      name: ebs-storage
  volumes:
  - name: ebs-storage
    persistentVolumeClaim:
      claimName: ebs-pvc
########## Secret Volume Example ##########
---
apiVersion: v1
kind: Pod

metadata:
  name: secret-1401
  namespace: alpha
  labels:
    app: secret-1401
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: secret-1401
    image: busybox
    command:
    - /bin/sh
    - -c
    - sleep 4800
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume


---
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        run: secret-1401
      name: secret-1401
      namespace: admin1401
    spec:
      volumes:
      - name: secret-volume
        # secret volume
        secret:
          secretName: dotfile-secret
      containers:
      - command:
        - sleep
        - "4800"
        image: busybox
        name: secret-admin
        # volumes' mount path
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"