apiVersion: v1
kind: Pod
metadata:
  name: high-performance-pod
  labels:
    app: high-performance-pod
spec:
  restartPolicy: Always            # Always, OnFailure, Never
  containers:
  - name: high-performance-pod
    image: nginx
    volumeMounts:
    - name: high-performance-vol
      mountPath: /tmp
  volumes:
  - name: high-performance-vol
    persistentVolumeClaim:
      claimName: high-performance-pvc