apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: high-performance-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce                # ReadWriteOnce, ReadWriteMany, ReadOnlyMany, ReadWriteOncePod