apiVersion: v1
kind: Service
metadata:
  name: head-svc
spec:
  selector:
    app: head-state
  clusterIP: None                     # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: head-state
spec:
  replicas: 1
  serviceName: head-svc
  selector:
    matchLabels:
      app: head-state
  template:
    metadata:
      labels:
        app: head-state
    spec:
      restartPolicy: Always            # Always, OnFailure, Never
      containers:
      - name: head-state-container
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "rootpassword"
        