---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckad15-depl-svcn
  labels:
    app: nginx-app
    env: demo 
spec: 
  replicas: 2
  template:
    metadata:
      name: nginx-app
      labels:
        env: demo 
        app: nginx-app
        type: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
          - containerPort: 80
  selector: 
    matchLabels:
      env: demo
      app: nginx-app
      type: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: ckad15-service-svcn
spec:
  selector:
    app: nginx-app
    env: demo
    type: nginx
  type: NodePort                      # ClusterIP, NodePort, LoadBalancer, ExternalName
  ports:
  - nodePort: 30085
    port: 80
    targetPort: 80