apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: demo 
    app: nginx-app
    type: nginx
spec:
  containers:
    - name: nginx-container 
      image: nginx:latest
      ports:
      - containerPort: 8080

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: nginx-rc
   labels:
    env: demo 
    app: nginx-app
    type: nginx
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo 
        app: nginx-app
        type: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
          - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
    env: demo 
spec: 
  replicas: 1
  template:
    metadata:
      name: nginx-app
      labels:
        env: demo 
        app: nginx-app
        type: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
          - containerPort: 80
  selector: 
    matchLabels:
      env: demo
      app: nginx-app
      type: nginx


